apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: gcr.io/[PROJECT_ID]/[IMAGE_NAME]:[IMAGE_TAG]  # Replace with your Docker image details
          ports:
            - containerPort: 80  # Port your application is listening on
          # Add additional container configuration here if needed
      # Add volume mounts, environment variables, and other specifications as needed
