# Generated by Django 3.2.21 on 2023-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230914_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
