# Generated by Django 3.2.21 on 2023-09-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
