# Generated by Django 3.2.21 on 2023-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230928_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
